[package]
name = "game"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = { version = "0.29.0", features = [
    "event-stream",
    "libc",
    "osc52",
    "serde",
] }
rand = { version = "0.9.1" }
serde = { version = "1.0.219", features = ["derive"] }
